### ISSUE TITLE
Warn if size is bigger than allowed by CG

### ISSUE THREAD

**Issue by andre2007** [Agade09/CG-Send-Binary#2]
@Agade09 Could you output a warning if the size of the resulting cpp is bigger than allowed by CG?

**Comment by Agade09** [comment]
Should now warn you if exceeding, and omit the source code if that allows the code to be below the limit.

**Comment by andre2007** [comment]
@Agade09 thanks a lot again.
Could I ask you for 2 more things?

- could you create a github release and add as artifact the compiled executable? I plan to write a small article how you can use the D Programming Language using your tool on CG. Just pointing to an executable is much more easier than explaining what needs to be installed on a system for compiling a cpp application...

- by starting your tool with argument --version, it could show your name, the version of the tool and the link to your github repository

**Comment by Agade09** [comment]
Done

**Comment by andre2007** [comment]
Great! Thanks a lot.
